name: CI/CD Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context:
          - backend/init_db
          - backend/task_manager
          - backend/user_manager
          - frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.4.0
        with:
          context: ${{ matrix.context }}
          push: false
          tags: user/${{ matrix.context }}:latest
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: pwd
      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "."
          mypy-options: ""
          pylint-options: ""
          isort-options: ""
          django: false









        
